/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Cisco (https://sketchfab.com/Ciscow)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cyberpunk-desk-8bc4ca48b2e244ff8b5ba714a2ec1963
title: Cyberpunk Desk
*/

import React, { Suspense, useRef } from 'react'
import { useGLTF, OrbitControls, OrthographicCamera, PerspectiveCamera } from '@react-three/drei'
import { Canvas, useFrame } from "react-three-fiber"
import styled from "styled-components"

const GridContainer = styled.div`
  display: flex;
  width: 100%;
  justify-content: center;
`

function CyberPunkModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glb/cyberpunk_desk.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group 
        rotation={[-Math.PI / 2, 0, 0]}
        position={[7.3,-3.9,0]}
      >
        <mesh geometry={nodes.Object_2.geometry} material={materials['1041']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['1042']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['1043']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['1053']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['1054']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['1055']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['1045']} />
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/cyberpunkDesk.gltf')


export default function CyberPunkDesk() {
  return (
    <GridContainer>
      <Canvas 
        style={{
          backdropFilter: "blur(10px)",
          backgroundColor: "rgb(255,255,255, 0.1)",
          borderRadius: "10px",
          margin:"10px",
          height: "38vh",
          width: "50vh",
          zIndex: "1"
        }}
        camera={{
          fov: 12.6, 
          near: 3, 
          position: [0,4,16]
          // far: 3
        }}
      >
        <ambientLight intensity={1} />
        <spotLight intensity={0.5} angle={0.1} penumbra={1} position={[10, 15, 10]} castShadow />
          <Suspense fallback={null}>
            <CyberPunkModel />
          </Suspense>
          <OrbitControls />
      </Canvas>
    </GridContainer>
  )
}
